export const invitation = {
  couple: {
    first: "Искендер",
    second: "Айдай",
  },
  event: {
    date: "2026-09-07T16:00:00+06:00",
    displayDate: "07 · 09 · 2026",
    weekday: { ru: "Понедельник", en: "Monday" },
    banquetTime: "16:00",
  },
  venue: {
    name: "Ресторан ROYAL",
    city: { ru: "г. Бишкек, Кыргызстан", en: "Bishkek, Kyrgyzstan" },
    address: "ул. Мадиева, 18/1",
    mapUrl: "https://2gis.kg/bishkek/search/royal%20%D1%80%D0%B5%D1%81%D1%82%D0%BE%D1%80%D0%B0%D0%BD/firm/70000001039587169/74.642512%2C42.823918?m=74.642512%2C42.823918%2F14.22",
  },
} as const;

export type Language = "ru" | "en";

export const copy = {
  ru: {
    invitation: "Приглашение на свадьбу",
    open: "открыть приглашение",
    skip: "пропустить",
    greeting: "Дорогие друзья и родные!",
    greetingMale: "Дорогой",
    greetingFemale: "Дорогая",
    greetingFriends: "Дорогие",
    lead: "Этот день настал — мы женимся!",
    body: "И очень хотим разделить с вами наш долгожданный праздник любви.",
    sub: "Ваше присутствие станет для нас самым ценным подарком.",
    countdown: "До начала торжества",
    days: "дней",
    hours: "часов",
    minutes: "минут",
    seconds: "секунд",
    details: "Детали торжества",
    date: "Дата",
    time: "Время",
    place: "Место",
    openMap: "Открыть на карте",
    banquet: "Начало банкета",
    footer: "С нетерпением ждём встречи с вами!",
  },
  en: {
    invitation: "Wedding invitation",
    open: "open invitation",
    skip: "skip",
    greeting: "Dear friends and family!",
    greetingMale: "Dear",
    greetingFemale: "Dear",
    greetingFriends: "Dear",
    lead: "The day has come — we are getting married!",
    body: "We would love to share our long-awaited celebration of love with you.",
    sub: "Your presence will be the most meaningful gift to us.",
    countdown: "Counting down to the celebration",
    days: "days",
    hours: "hours",
    minutes: "minutes",
    seconds: "seconds",
    details: "Event details",
    date: "Date",
    time: "Time",
    place: "Venue",
    openMap: "Open in Maps",
    banquet: "Banquet begins",
    footer: "We can’t wait to celebrate with you!",
  },
} as const;
